##########

# This script is designed to clean up all the files generated by dftb
# (during the ase simulations)
# Will Also Delete the Input Files 

##########

# Remove Output files 
rm band.out detailed.out dftb.out geo_end.gen geo_end.xyz 

# Remove Input Files 
rm dftb_in.hsd dftb_pin.hsd
